### PR TITLE
Feat: Follow, unfollow and explore page

### PR DESCRIPTION
**Pull request by bharati-21**
This PR contains the following
- Users can follow/ unfollow any user
- The user feed is organized with posts only from following users
- The explore feed is organized with posts from users not followed
- Added user suggestion sidebar

### CODE REVIEW

**Comment by Ranjeetk489** [comment]
Tried accessing your deployed app but it's leading to blank page. Your app is loading well as your initial redux states are showing up in the devtools so maybe lil bit of debugging is required. Please take a look around.

**Comment by bharati-21** [comment]
> Tried accessing your deployed app but it's leading to blank page. Your app is loading well as your initial redux states are showing up in the devtools so maybe lil bit of debugging is required. Please take a look around.

Thank you so much for informing. My bad. I forgot to update the environment variables on netlify. Can you please check now?

**Review by romabulani — APPROVED** [review]
- Follow Unfollow Users Functionalities along with explore and home pages are working as intended.
- Liked the Modular code structure.
- PR is ready to merge.

**Review by sashaboi — APPROVED** [review]
Code is very well written
Liked the folder structure
Looks good to merge.

**Comment by bharati-21** [comment]
> Code is very well written Liked the folder structure Looks good to merge.

Thank you for your review.

**Pull request merged**
