### PR TITLE
Feat: Edit, Delete Post

### PR DESCRIPTION
**Pull request by bharati-21**
This PR contains the following features:
- A user can click on the 3 horizontal dots icon at the top right corner of the post and choose "More options"
- User can click on the edit button, which will open the contents of the post on a modal and user can edit the content and save.
- When user clicks on the delete button, the selected post is deleted.

### CODE REVIEW

**Review by tanishk15sharma — APPROVED** [review]
great `commit` messages and naming convention .

**Review by ravikumar0403 — APPROVED** [review]
Liked the folder structure
Very well written code

**Comment by bharati-21** [comment]
> great `commit` messages and naming convention .

Thank you for your review!

**Comment by bharati-21** [comment]
> Liked the folder structure Very well written code

Thank you for your review!

**Pull request merged**
