### PR TITLE
Feat: Comments, single post page

### PR DESCRIPTION
**Pull request by bharati-21**
This PR contains the following-
- Users can click on any post that takes them to the signle page view for that post
- Users can see the list of comments from other users
- Users can also input theit comments for the selected post
- Users can see a circular progress counter that displays the number of characters left to be entered in the reply

### CODE REVIEW

**Review by sashaboi — APPROVED** [review]
everything looks amazing , great work , good to merge ! 

A few suggestions : the hompage CTA button of signup leads to some error with some import missing hope that will be fixed later. 

also , if a rather large comment is made, it breaks the page and css and goes out. hope some wrapping is going to be added later to improve ux as well!

**Review by krgarima — APPROVED** [review]
Hey , you can add a feature where on pressing the enter button, user can add his comment to a post.  I like the UI.

**Comment by bharati-21** [comment]
> everything looks amazing , great work , good to merge !
> 
> A few suggestions : the hompage CTA button of signup leads to some error with some import missing hope that will be fixed later.
> 
> also , if a rather large comment is made, it breaks the page and css and goes out. hope some wrapping is going to be added later to improve ux as well!

- Yes, I shall look into the missing export. Thank you for pointing it out.
- Yes, I have made style changes to accomodate large comment texts. Thanks again for pointing out.
- These will reflect in the next PR.
Thank you for your review.

**Comment by bharati-21** [comment]
> Hey , you can add a feature where on pressing the enter button, user can add his comment to a post. I like the UI.

- As the comment/ post could be mutiline and also since it's a textarea, the "submit on enter" is not enabled (it's a default feature in a form actually). Referred twitter for this. 
Thank you for your review!

**Pull request merged**
