### PR TITLE
Feat: Theme

### PR DESCRIPTION
**Pull request by bharati-21**
This PR contains the following-
- Users can now change and toggle the app theme to either dark/ light.
- The preference is stored in the local storage so that the next time user visits the app, the theme is automatically selected accorfing to preference.
- All pages/ components accomodate for theme change

### CODE REVIEW

**Review by kumsomi — APPROVED** [review]
- The toggle is working fine. Theme is getting saved in my local storage, as expected.
- Code is clean
- Looks good to me

**Comment by bharati-21** [comment]
> * The toggle is working fine. Theme is getting saved in my local storage, as expected.
> * Code is clean
> * Looks good to me

Thank you for your review.

**Review by sonishreyas — APPROVED** [review]
Code looks good and easy to understand. Like the folder structure

**Comment by bharati-21** [comment]
> Code looks good and easy to understand. Like the folder structure

Thank you for your review.

**Pull request merged**
